#!/bin/bash
# Every check the platform has, in one command, in a fixed order.
#
# The tests are standalone scripts rather than a pytest suite, so this runs each in its own
# interpreter: one test's compiled programs and device buffers then cannot affect the next, and a
# test that runs out of device memory takes only itself down.
#
# On the processor (the default), where every arithmetic result is deterministic:
#   bash tests/run_all.sh
# On the graphics card, through the serval05 lock (one graphics-card command at a time):
#   bash /p/rlprojects/RND/09_parallelization/locks/gpu_run.sh \
#     "cd <this platform folder> && bash tests/run_all.sh gpu"
#
# Six tests are skipped on the card and say so: the uncompiled-execution comparison, which runs a
# whole iteration outside the compiler and takes very long there, and five agent-only checks whose
# results do not depend on the device.
#
# Do not edit this file while a run of it is in progress. Bash reads a script as it executes, so an
# edit mid-run leaves it reading from a byte offset that no longer means what it did — over shared
# storage that surfaces as "error reading input file: Stale file handle" and the run dies after its
# last test without printing the summary line.
set -uo pipefail
WHERE="${1:-cpu}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON=/p/rlprojects/RND/.venvs/platform_jax/bin/python
export PYTHONNOUSERSITE=1
[ "$WHERE" = "cpu" ] && export JAX_PLATFORMS=cpu

# both lists are written across several lines for reading, then collapsed to single-spaced words:
# the membership test below looks for " <name> ", and a name followed by a newline rather than a
# space would not match, so a skipped test would silently run
CPU_ONLY="agents/test_jax_ppo.py agents/test_sweep_jax.py agents/test_hoist_equivalence.py
          agents/test_flat_params_equivalence.py agents/test_copy_seed_offset.py
          integration/test_jit_eager_equivalence.py"
ALL="golden_09/test_golden_parity.py
     agents/test_jax_ppo.py
     agents/test_sweep_jax.py
     agents/test_copy_seed_offset.py
     agents/test_hoist_equivalence.py
     agents/test_flat_params_equivalence.py
     bonuses/test_registry.py
     bonuses/test_none_has_no_bonus_arithmetic.py
     bonuses/test_visit_count.py
     bonuses/test_visit_count_learning_sanity.py
     parity_07/test_visit_count_against_07.py
     envs/test_antmaze_mjx.py
     envs/test_antmaze_parity_cpu_mujoco.py
     envs/test_antmaze_compose.py
     agents/test_discrete_actor.py
     envs/test_montezuma_adapter.py
     envs/test_montezuma_compose.py
     copy_isolation/test_bonus_copy_isolation.py
     integration/test_jit_eager_equivalence.py"
CPU_ONLY=" $(echo $CPU_ONLY) "
ALL="$(echo $ALL)"

failed=0
for t in $ALL; do
  if [ "$WHERE" = "gpu" ] && [[ "$CPU_ONLY" == *" $t "* ]]; then
    printf '%-52s SKIPPED on the card\n' "$t"
    continue
  fi
  # the log name carries the device, so a processor run and a card run started together — which
  # is the normal way to run both — cannot overwrite each other's output
  start=$(date +%s)
  log="/tmp/platform_test_${WHERE}_$(basename "$t" .py).log"
  if "$PYTHON" "$HERE/$t" > "$log" 2>&1; then
    printf '%-52s pass  %3ds\n' "$t" "$(( $(date +%s) - start ))"
  else
    printf '%-52s FAIL  %3ds  (log %s)\n' "$t" "$(( $(date +%s) - start ))" "$log"
    failed=$((failed + 1))
  fi
done
echo "--- $failed failed ---"
exit $failed
